version: '3.8'

services:

  api:
    env_file:
      - .env-live
    build: .
    ports:
      - "80:80"
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
     - .:/usr/src/app

  mongo:
    image: mongo
    env_file:
      - .env-live
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: mongod --auth
    ports:
      - "27017:27017"